# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'st.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(594, 688)
        Form.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 0, 421, 121))
        self.label.setStyleSheet("font: 20pt \"Franklin Gothic Heavy\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(320, 290, 181, 31))
        self.lineEdit.setStyleSheet("font: 8pt \"Franklin Gothic Medium\";\n"
"color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.295455 rgba(102, 126, 255, 255), stop:0.971591 rgba(0, 217, 255, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 330, 181, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"  background-color: #232323;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #000000;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #7400C7;\n"
"  border: 3px solid #9ac3fe;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(90, 550, 91, 31))
        self.comboBox.setStyleSheet("background-color: rgb(116, 0, 199);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.295455 rgba(102, 126, 255, 255), stop:0.971591 rgba(0, 217, 255, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 340, 91, 31))
        self.comboBox_2.setStyleSheet("background-color: rgb(116, 0, 199);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.295455 rgba(102, 126, 255, 255), stop:0.971591 rgba(0, 217, 255, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 290, 91, 31))
        self.comboBox_3.setStyleSheet("background-color: rgb(36, 0, 61);\n"
"background-color: rgb(116, 0, 199);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.295455 rgba(102, 126, 255, 255), stop:0.971591 rgba(0, 217, 255, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 240, 81, 31))
        self.label_3.setStyleSheet("font: 8pt \"Franklin Gothic Heavy\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(90, 390, 81, 31))
        self.label_4.setStyleSheet("font: 8pt \"Franklin Gothic Heavy\";")
        self.label_4.setObjectName("label_4")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 440, 91, 31))
        self.comboBox_4.setStyleSheet("background-color: rgb(116, 0, 199);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.295455 rgba(102, 126, 255, 255), stop:0.971591 rgba(0, 217, 255, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(90, 490, 91, 31))
        self.comboBox_5.setStyleSheet("background-color: rgb(36, 0, 61);\n"
"background-color: rgb(116, 0, 199);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.295455 rgba(102, 126, 255, 255), stop:0.971591 rgba(0, 217, 255, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(80, 170, 441, 41))
        self.label_5.setStyleSheet("font: 15pt \"Franklin Gothic Heavy\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(350, 550, 111, 41))
        self.label_6.setStyleSheet("font: 15pt \"Franklin Gothic Heavy\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 440, 181, 31))
        self.lineEdit_2.setStyleSheet("font: 8pt \"Franklin Gothic Medium\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 480, 181, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(spread:pad, cx:0.494318, cy:0.545, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(36, 0, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(255, 176, 176, 167), stop:0.3 rgba(255, 151, 151, 92), stop:0.4 rgba(255, 125, 125, 51), stop:0.5 rgba(255, 76, 76, 205), stop:0.52 rgba(255, 76, 76, 205), stop:0.6 rgba(255, 180, 180, 84), stop:1 rgba(255, 255, 255, 0));\n"
"  background-color: #232323;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #000000;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #7400C7;\n"
"  border: 3px solid #9ac3fe;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#fdfdfd;\">ComboBox</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Form", "введите сумму"))
        self.pushButton_3.setText(_translate("Form", "конвертировать"))
        self.comboBox.setItemText(0, _translate("Form", "США"))
        self.comboBox.setItemText(1, _translate("Form", "КНДР"))
        self.comboBox.setItemText(2, _translate("Form", "КНР"))
        self.comboBox.setItemText(3, _translate("Form", "РФ"))
        self.comboBox.setItemText(4, _translate("Form", "ЮАР"))
        self.comboBox_2.setItemText(0, _translate("Form", "доллар"))
        self.comboBox_2.setItemText(1, _translate("Form", "евро"))
        self.comboBox_2.setItemText(2, _translate("Form", "рубль"))
        self.comboBox_2.setItemText(3, _translate("Form", "стерлинг"))
        self.comboBox_2.setItemText(4, _translate("Form", "фунт"))
        self.comboBox_3.setItemText(0, _translate("Form", "доллар"))
        self.comboBox_3.setItemText(1, _translate("Form", "евро"))
        self.comboBox_3.setItemText(2, _translate("Form", "рубль"))
        self.comboBox_3.setItemText(3, _translate("Form", "стерлинг"))
        self.comboBox_3.setItemText(4, _translate("Form", "фунт"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">из -&gt; в</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">из -&gt; в</span></p></body></html>"))
        self.comboBox_4.setItemText(0, _translate("Form", "миллиметр"))
        self.comboBox_4.setItemText(1, _translate("Form", "сантиметр"))
        self.comboBox_4.setItemText(2, _translate("Form", "дециметр"))
        self.comboBox_4.setItemText(3, _translate("Form", "метр"))
        self.comboBox_4.setItemText(4, _translate("Form", "киллометр"))
        self.comboBox_5.setItemText(0, _translate("Form", "миллиметр"))
        self.comboBox_5.setItemText(1, _translate("Form", "сантиметр"))
        self.comboBox_5.setItemText(2, _translate("Form", "дециметр"))
        self.comboBox_5.setItemText(3, _translate("Form", "метр"))
        self.comboBox_5.setItemText(4, _translate("Form", "киллометр"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">Конвертатор</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">страна</span></p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "введите значение"))
        self.pushButton_4.setText(_translate("Form", "конвертировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
