# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vr.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(979, 644)
        Form.setStyleSheet("\n"
"background-color: rgb(147, 147, 147);\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 50, 571, 81))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(400, 90, 201, 31))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 430, 171, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 500, 171, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 160, 101, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 180, 201, 31))
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 41, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 220, 51, 51))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(620, 50, 201, 31))
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 230, 201, 31))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(450, 170, 51, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(450, 220, 51, 51))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(510, 180, 201, 31))
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(510, 230, 201, 31))
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; color:#000000;\">Площадь прямоугольного треугольника (ответ) -&gt;</span></p><p align=\"justify\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; color:#000000;\">Площадь треугольника (ответ) -&gt;</span></p><p align=\"justify\"><span style=\" color:#aa557f;\"><br/></span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "вычислить"))
        self.pushButton_2.setText(_translate("Form", "очистить"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:24pt; font-weight:600; color:#000000;\">а=</span></p><p align=\"justify\"><span style=\" font-size:24pt; font-weight:600; color:#550000;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:24pt; font-weight:600; color:#000000;\">б=</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:24pt; font-weight:600; color:#000000;\">а=</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:24pt; font-weight:600; color:#000000;\">h=</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
